### ISSUE TITLE
[BUG]: broken indents in annotations

### ISSUE THREAD

**Issue by kolobabka** [pavel-collab/Bachelor-Thesis-Template#19]
There is some troubles with indents in the current annotation template.
F.E:
![image](https://github.com/pavel-collab/Bachelor-Thesis-Template/assets/70813857/43a2187f-ad4f-46f5-a728-3590838131b9)

You can see that "сложных алгоритмических паттернов" is tricky. 

Let's do something with that

**Comment by kolobabka** [comment]
![image](https://github.com/pavel-collab/Bachelor-Thesis-Template/assets/70813857/3f551341-cf6a-44e6-a504-fefca708adfa)

Seems to be resolved

**Comment by Exactlywb** [comment]
I came across exactly the same problem, but couldn't figure out how to fix it. From my personal observations, I can only say that this seems to happen because of begin{center}. I've accepted your patch for now, but I suggest leaving this issue open until a better solution is found.

**Comment by kolobabka** [comment]
>  I can only say that this seems to happen because of begin{center}.
Unfortunately, this bug has been
